# platform :ios, '9.0'

target 'TransartistryApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TransartistryApp
pod 'SwiftLint'
pod 'SnapKit', '~> 5.0.0'
pod 'RxSwift', '6.5.0'
pod 'RxCocoa', '6.5.0'
pod 'LGButton'
pod 'TICoordinatorKit', :git => 'https://github.com/TouchInstinct/TICoordinatorKit.git', :branch => 'master'

  target 'TransartistryAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TransartistryAppUITests' do
    # Pods for testing
  end

end
