# platform :ios, '9.0'

target 'TransartistryApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TransartistryApp

  target 'TransartistryAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TransartistryAppUITests' do
    # Pods for testing
  end

end
